version: "3"
services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - /srv/docker/influxdb:/var/lib/influxdb
  garie-lighthouse:
    image: "garie/lighthouse"
    ports:
      - 3000:3000
    environment:
      - HOST=influxdb
    volumes:
      - /srv/docker/garie-config.json:/usr/src/garie-lighthouse/config.json
      - /srv/docker/plugins/garie-lighthouse/reports:/usr/src/garie-lighthouse/reports
      - /srv/docker/plugins/garie-lighthouse/logs:/usr/src/garie-lighthouse/logs
    depends_on:
      - influxdb
  garie-browsertime:
    image: "garie/browsertime"
    ports:
      - 3001:3000
    environment:
      - HOST=influxdb
      - REPORT_DIR
    volumes:
      - /srv/docker/garie-config.json:/usr/src/garie-browsertime/config.json
      - /srv/docker/plugins/garie-browsertime/reports:/usr/src/garie-browsertime/reports
      - /srv/docker/plugins/garie-browsertime/logs:/usr/src/garie-browsertime/logs
      - /var/run/docker.sock:/run/docker.sock
      - ${DOCKER_PATH}:/usr/bin/docker
    depends_on:
      - influxdb
  garie-pagespeed-insights:
    image: "garie/pagespeed-insights"
    ports:
      - 3002:3000
    environment:
      - HOST=influxdb
      - PAGESPEED_INSIGHTS_KEY
    volumes:
      - /srv/docker/garie-config.json:/usr/src/garie-pagespeed-insights/config.json
      - /srv/docker/plugins/garie-pagespeed-insights/logs:/usr/src/garie-pagespeed-insights/logs
    depends_on:
      - influxdb
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - "/srv/docker/grafana_data:/var/lib/grafana"
      - "/srv/docker/config/grafana/provisioning:/etc/grafana/provisioning"
      - "/srv/docker/config/grafana/grafana.ini:/etc/grafana/grafana.ini"
    depends_on:
      - influxdb
    user: ${CURRENT_UID}
  chronograf:
    image: "chronograf:latest"
    ports:
      - 8888:8888
    depends_on:
      - influxdb
